### ISSUE TITLE
疑问1.queryKeyword 

### ISSUE THREAD

**Issue by fandexiaohao** [Strelizia02/ArknightsAPI#4]
queryKeyword 
这里明明用一个switch就可以解决的问题.
为什么要加上map和枚举来.
        switch (c) {
            case "菜单":
            case "功能":
                result ="";
                break;
这样写更加直观也方便.

却硬要另外在写两个文件. 就为了弄map和枚举...也就是说,修改的时候,需要改动三个文件.

虽然对比string和对比int  可能有性能差距. 因为我不懂java,所以这是我的猜测.
可是GetClass方法里面是static, 又必须每次调用的时候生成map. 这里又是性能浪费呀.

虽然带着点怒气, 但是真的是被这些折磨的人的一些疑问.

还有为什么不把 详细菜单放到类里面,单独写一个属性放, 当然最好放一个方法里面把, 可以折叠.

**Comment by Strelizia02** [comment]
1.枚举类实际是int型，int型的对比直接对比值，String的对比要先获取java堆里的字符串常量再进行值对比，int型效率比较高。
2.连着写一堆case我嫌他排版丑，所以通过枚举类+map的形式来实现，如果是java12的话，支持case 1,2:这种格式，可惜我是java8。
详细菜单放到类里面也可以，这个确实占用了太多行数，后期会优化掉
